create table if not exists public.plans (id uuid primary key default gen_random_uuid(),code text not null unique,name text not null,description text,monthly_price numeric(12,2) not null default 0 check(monthly_price>=0),currency text not null default 'ARS',limits jsonb not null default '{}'::jsonb,features jsonb not null default '{}'::jsonb,active boolean not null default true,sort_order integer not null default 0,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
insert into public.plans(code,name,description,limits,features,sort_order) values
('starter','Inicial','Para un taller que comienza a digitalizar su operación','{"users":1,"clients":250,"monthlyOrders":100,"storageMb":500}','{"agenda":true,"cash":true,"receipts":true,"gallery":false,"reports":false}',10),
('professional','Profesional','Gestión completa para un negocio de detailing en crecimiento','{"users":3,"clients":2000,"monthlyOrders":1000,"storageMb":5000}','{"agenda":true,"cash":true,"receipts":true,"gallery":true,"reports":true}',20),
('business','Negocio','Para equipos con mayor volumen y necesidades avanzadas','{"users":10,"clients":10000,"monthlyOrders":5000,"storageMb":20000}','{"agenda":true,"cash":true,"receipts":true,"gallery":true,"reports":true,"prioritySupport":true}',30)
on conflict(code) do update set name=excluded.name,description=excluded.description,limits=excluded.limits,features=excluded.features,sort_order=excluded.sort_order;
create table if not exists public.organization_subscriptions (organization_id uuid primary key references public.organizations(id) on delete cascade,plan_id uuid not null references public.plans(id),status text not null default 'trialing' check(status in('trialing','active','past_due','paused','cancelled')),trial_ends_at timestamptz,current_period_starts_at timestamptz not null default now(),current_period_ends_at timestamptz,external_customer_id text,external_subscription_id text,cancel_at_period_end boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
insert into public.organization_subscriptions(organization_id,plan_id,status) select o.id,p.id,'active' from public.organizations o cross join public.plans p where p.code='professional' on conflict(organization_id) do nothing;
alter table public.plans enable row level security; alter table public.organization_subscriptions enable row level security;
drop policy if exists authenticated_plans_read on public.plans; create policy authenticated_plans_read on public.plans for select to authenticated using(active=true);
drop policy if exists tenant_access on public.organization_subscriptions; create policy tenant_access on public.organization_subscriptions for select to authenticated using(organization_id=public.current_organization_id());
create or replace function public.current_usage() returns jsonb language sql stable security definer set search_path=public as $$ select jsonb_build_object('users',(select count(*) from public.profiles where organization_id=public.current_organization_id() and active=true),'clients',(select count(*) from public.clients where organization_id=public.current_organization_id() and deleted_at is null),'monthlyOrders',(select count(*) from public.work_orders where organization_id=public.current_organization_id() and deleted_at is null and created_at>=date_trunc('month',now()))); $$;
grant execute on function public.current_usage() to authenticated;

